### PR TITLE
Add TOSCA template and types for ARC

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
To be merged after https://github.com/grycap/im-dashboard/pull/545

xref: https://www.nordugrid.org/arc/arc7/index.html

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
Question: In a test deployment of this TOSCA template for ARC via IM Dashboard, the ARC playbook runs in different order depending on the node type of the Slurm cluster:

* For the front-end node of the Slurm cluster: the ARC playbook runs after the Slurm playbook; this is the desired order.

* For the worker nodes of the Slurm cluster: the ARC playbook runs before the Slurm playbook; this is not desired.

How can I make the ARC playbook to run after the Slurm playbook for all nodes in the Slurm cluster?

Thanks!

**Comment by sebastian-luna-valero** [comment]
Sorry, I don't know why I am getting these errors
* `InvalidTypeError: Type "tosca.nodes.indigo.ARCfe" is not a valid type`
* `InvalidTypeError: Type "tosca.nodes.indigo.ARCwn" is not a valid type`
* `syntax-check[specific]: the role 'arc' was not found`

Could you please help?

**Comment by sebastian-luna-valero** [comment]
Thank you very much @micafer

**Review by micafer — APPROVED** [review]
LGTM

**Comment by sebastian-luna-valero** [comment]
Should I replace
* https://raw.githubusercontent.com/sebastian-luna-valero/tosca-upv/arc/artifacts/arc.yml
* with: https://raw.githubusercontent.com/grycap/tosca/main/artifacts/arc.yml

and:
* https://raw.githubusercontent.com/sebastian-luna-valero/tosca-upv/arc/custom_types.yaml
* with: https://raw.githubusercontent.com/grycap/tosca/main/custom_types.yaml

?

Or should I wait until we test this deployment using IM-dev?

**Comment by sebastian-luna-valero** [comment]
Sure: https://github.com/grycap/tosca/pull/148

**Pull request merged**
