### PR TITLE
Add Dynamic DNS to k8s and slurm

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
Hello,

Would this be useful in combination with `cert-manager` when deploying k8s?

Thanks,
Sebastian

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
Ready for review.

**Comment by micafer** [comment]
Sorry @sebastian-luna-valero I was biy busy.

**Review by micafer — COMMENTED** [review]
LGTM

**Review by micafer — COMMENTED** [review]
LGTM

**Review by micafer — COMMENTED** [review]
LGTM

**Comment by micafer** [comment]
they are available in the devel instance.

**Comment by sebastian-luna-valero** [comment]
my tests in the devel instance seems to work, thanks!

**Comment by micafer** [comment]
just to let you know that they have been made available also in the prod instance.

**Comment by sebastian-luna-valero** [comment]
Thank you very much!

**Pull request merged**
