### PR TITLE
ARC: Custom types back to upstream repo

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
Hi,

Are these changes ok to test the new template using IM-dev?

Thanks!

**Review by micafer — APPROVED** [review]
LGTM

**Comment by micafer** [comment]
> Hi,
> 
> Are these changes ok to test the new template using IM-dev?
> 
> Thanks!

Template added in the devel instance.
Could you test it?

Best regards.

**Comment by sebastian-luna-valero** [comment]
Hi,

Do you know why the playbooks and roles are run twice in IM-dev for the Slurm+ARC template (see above)?

**Comment by micafer** [comment]
Could you send me by mail de full contextualization log?

**Pull request merged**
