### PR TITLE
Register DNS hostname with Dynamic DNS before deploying MinIO with Compose

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
Otherwise, let's encrypt can't complete the challenge to issue the HTTPS certificate.

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
Hello,

This PR is ready to be reviewed, could you please have a look?

Thanks!

**Comment by sebastian-luna-valero** [comment]
Hello,

This PR is ready to be reviewed, could you please have a look?

Thanks!

**Comment by micafer** [comment]
The order in the TOSCA template does not assure that these configuration tasks will me made before, you must add a "dependency". Let me add it.

**Comment by sebastian-luna-valero** [comment]
Ah, I see, I learnt something new today, many thanks!

**Comment by micafer** [comment]
Could you please test it in the IM devel instance?

**Comment by sebastian-luna-valero** [comment]
It's working, many thanks!

**Pull request merged**
